config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :schedules
  resources :comments
  resources :discounts
  resources :plays
  resources :teathers
  devise_for :users

  

  root 'home#index'

end

app/models/teather.rb
class Teather < ActiveRecord::Base
	has_many :discounts
	has_many :comments
	has_many :plays
end

app/controllers/teathers_controller.rb
class TeathersController < ApplicationController
  before_action :set_teather, only: [:show, :edit, :update, :destroy]

  # GET /teathers
  # GET /teathers.json
  def index
    @teathers = Teather.all
  end

  # GET /teathers/1
  # GET /teathers/1.json
  def show
  end

  # GET /teathers/new
  def new
    @teather = Teather.new
  end

  # GET /teathers/1/edit
  def edit
  end

  # POST /teathers
  # POST /teathers.json
  def create
    @teather = Teather.new(teather_params)

    respond_to do |format|
      if @teather.save
        format.html { redirect_to @teather, notice: 'Teather was successfully created.' }
        format.json { render :show, status: :created, location: @teather }
      else
        format.html { render :new }
        format.json { render json: @teather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teathers/1
  # PATCH/PUT /teathers/1.json
  def update
    respond_to do |format|
      if @teather.update(teather_params)
        format.html { redirect_to @teather, notice: 'Teather was successfully updated.' }
        format.json { render :show, status: :ok, location: @teather }
      else
        format.html { render :edit }
        format.json { render json: @teather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teathers/1
  # DELETE /teathers/1.json
  def destroy
    @teather.destroy
    respond_to do |format|
      format.html { redirect_to teathers_url, notice: 'Teather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teather
      @teather = Teather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teather_params
      params.require(:teather).permit(:name, :address, :manager, :mobile, :phone, :web_site, :logo, :description, :latitude, :longitude)
    end
end

app/helpers/teathers_helper.rb
module TeathersHelper
end

app/views/teathers/_form.html.erb
<%= form_for(@teather) do |f| %>
  <% if @teather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teather.errors.count, "error") %> prohibited this teather from being saved:</h2>

      <ul>
      <% @teather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :manager %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :web_site %><br>
    <%= f.text_field :web_site %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teathers/edit.html.erb
<h1>Editing Teather</h1>

<%= render 'form' %>

<%= link_to 'Show', @teather %> |
<%= link_to 'Back', teathers_path %>

app/views/teathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teathers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Manager</th>
      <th>Mobile</th>
      <th>Phone</th>
      <th>Web site</th>
      <th>Logo</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teathers.each do |teather| %>
      <tr>
        <td><%= teather.name %></td>
        <td><%= teather.address %></td>
        <td><%= teather.manager %></td>
        <td><%= teather.mobile %></td>
        <td><%= teather.phone %></td>
        <td><%= teather.web_site %></td>
        <td><%= teather.logo %></td>
        <td><%= teather.description %></td>
        <td><%= teather.latitude %></td>
        <td><%= teather.longitude %></td>
        <td><%= link_to 'Show', teather %></td>
        <td><%= link_to 'Edit', edit_teather_path(teather) %></td>
        <td><%= link_to 'Destroy', teather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teather', new_teather_path %>

app/views/teathers/new.html.erb
<h1>New Teather</h1>

<%= render 'form' %>

<%= link_to 'Back', teathers_path %>

app/views/teathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teather.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @teather.address %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @teather.manager %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @teather.mobile %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @teather.phone %>
</p>

<p>
  <strong>Web site:</strong>
  <%= @teather.web_site %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @teather.logo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @teather.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @teather.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @teather.longitude %>
</p>

<%= link_to 'Edit', edit_teather_path(@teather) %> |
<%= link_to 'Back', teathers_path %>